spring:
  liquibase:
    change-log: classpath:/installers/impilo-gateway/schema/schema.xml
    enabled: true
  flyway:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
javers:
  sqlGlobalIdTableName: 'imp_jv_global_id'
  sqlCommitTableName: 'imp_jv_commit'
  sqlSnapshotTableName: 'imp_jv_snapshot'
  sqlCommitPropertyTableName: 'imp_jv_commit_property'


