spring:
  liquibase:
    change-log: classpath:/installers/impilo-gateway/schema/schema.xml
    enabled: true
  flyway:
    enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true


