description: Gateway application to support connectivity between the Impilo mobile app and E.HR server at the facility. Also manages bidirectional sync between the two components
name: Impilo E.HR Gateway
configurationsPath: installers/impilo-gateway/configuration.json
valueSetsPath: installers/impilo-gateway/value-sets.json
translations:
  - lang: en
    path: installers/impilo-gateway/i18n/en.json
  - lang: es
    path: installers/impilo-gateway/i18n/es.json
  - lang: fr
    path: installers/impilo-gateway/i18n/fr.json
  - lang: pt
    path: installers/impilo-gateway/i18n/pt.json
  - lang: sw
    path: installers/impilo-gateway/i18n/sw.json
  - lang: ig
    path: installers/impilo-gateway/i18n/ig.json
  - lang: ha
    path: installers/impilo-gateway/i18n/ha.json
  - lang: yo
    path: installers/impilo-gateway/i18n/yo.json
menus:
  - name: IMPILO.MENU.PATIENTS
    type: link
    route: patients
    icon: wc
  - name: IMPILO.MENU.STOCKS
    type: link
    route: stocks
    icon: cases
  - name: IMPILO.MENU.STOCK_REQUEST
    type: link
    route: stock-requests
    icon: cases
  - name: IMPILO.MENU.STOCK_ISSUANCE
    type: link
    route: stock-issuance
    icon: library_books
    position: 2
  - name: IMPILO.MENU.SYNC
    type: link
    route: sync
    icon: heroicons_outline:arrow-path
    position: 5
    authorities:
      - Facility tasks
  - name: IMPILO.MENU.REPORTS.TITLE
    type: dropDown
    icon: 'mat_solid:announcement'
    position: 3
    subs:
      - name: IMPILO.MENU.REPORTS.INDICATORS
        type: link
        route: reports/indicators
webRemotes:
  - remoteEntry: "/js/impilo-gateway/remoteEntry.js"
    remoteName: _5e665722_af83_4c02_82c0_48e62d779674
    modules:
      - name: StockModule
        ngModuleName: StockModule
        routePath: stocks
        title: IMPILO.TITLE.STOCKS
      - name: StockIssuanceModule
        ngModuleName: StockIssuanceModule
        routePath: stock-issuance
        title: IMPILO.TITLE.STOCK_ISSUANCE
      - name: PatientRouting
        routePath: patients
        title: IMPILO.TITLE.PATIENTS
      - name: StockRequestModule
        ngModuleName: StockRequestModule
        routePath: stock-requests
        title: IMPILO.TITLE.STOCK_REQUEST
      - name: IndicatorRouting
        routePath: reports/indicators
        title: IMPILO.MENU.REPORTS.INDICATORS
      - name: SyncRouting
        routePath: sync
        title: IMPILO.MENU.SYNC
        authorities:
          - Facility tasks
roles:
  - name: Facility administrator
    description: IMPILO.ROLES.FACILITY_ADMIN
    authority: ROLE_FACILITY_ADMIN
    permissions:
      - name: Facility tasks
  - name: EHR Sync
    permissions:
      - name: EHR Sync
